### PR TITLE
PSR-7 requests routing

### PR DESCRIPTION
**Pull request by rflavien**
The purpose is to allow the router to be used outside an Objective PHP application (see README for usage).

NB : to not introduce BC break I didn't update the RouterInterface but an update should be planned. An update is required for the following routers to support this new feature :
- PathMapperRouter
- FastRouteRouter

### CODE REVIEW

**Comment by rflavien** [comment]
As this PR will introduce a BC break, here is my proposal :  
uml

**Changes are :**
- making classes framework agnostic
- glueing this class with the `RouterMiddleware` class (for usage in Objective PHP)
- removing `public function url()` from `RouterInterface` (currently no usage, it can be introduce latter in a minor release)
- removing the `Dispatcher` class (for single responsibility library)

**Comment by fanshan** [comment]
Thank you very much @rflavien :-)

As you say, the major BC break is that the MetaRouter will no be a Middleware anymore.

On your work, we should split this repository in two other:

* One for the library with the reutilisability purpose in mind as describe in your UML diagram
* A package for the Objective-PHP application integration containing the `RouterMiddleware` and the configuration class

`Dispatcher` should be move to objective-php/application as an operation middleware.

What do you think about @gauthier ?

**Comment by gauthier** [comment]
Sounds good to me... only the BC break is annoying since we know for sure that some users already created custom routers based on RouterInterface. Wouldn't it be possible to create another interface dedicated to this new routing feature, and that would be applied on new routers only, so that former ones would be still working?

**Comment by gauthier** [comment]
@rflavien any thought regarding my previous comment?

**Comment by rflavien** [comment]
Yes, I'm glad you asked. I was thinking about an other interface without BC break (as you suggested) that supports PSR-7 and CLI requests. But I'm not sure that's the router Objective need. Is it worth spending some time on it ?

**Pull request closed without merging**
